/* eslint-disable */
// Auto-generated by: supabase gen types typescript
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      container_allocations: {
        Row: {
          container_id: string
          created_at: string
          id: string
          input_mode: Database["public"]["Enums"]["allocation_input_mode"]
          kilos: number
          percentage: number | null
          quality_grade_id: string
          sale_price_usd_kg: number
          updated_at: string
        }
        Insert: {
          container_id: string
          created_at?: string
          id?: string
          input_mode?: Database["public"]["Enums"]["allocation_input_mode"]
          kilos?: number
          percentage?: number | null
          quality_grade_id: string
          sale_price_usd_kg?: number
          updated_at?: string
        }
        Update: {
          container_id?: string
          created_at?: string
          id?: string
          input_mode?: Database["public"]["Enums"]["allocation_input_mode"]
          kilos?: number
          percentage?: number | null
          quality_grade_id?: string
          sale_price_usd_kg?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "container_allocations_container_id_fkey"
            columns: ["container_id"]
            isOneToOne: false
            referencedRelation: "containers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "container_allocations_quality_grade_id_fkey"
            columns: ["quality_grade_id"]
            isOneToOne: false
            referencedRelation: "quality_grades"
            referencedColumns: ["id"]
          },
        ]
      }
      containers: {
        Row: {
          capacity_kg: number
          created_at: string
          id: string
          sequence_number: number
          shipment_id: string
          size: Database["public"]["Enums"]["container_size"]
        }
        Insert: {
          capacity_kg: number
          created_at?: string
          id?: string
          sequence_number?: number
          shipment_id: string
          size?: Database["public"]["Enums"]["container_size"]
        }
        Update: {
          capacity_kg?: number
          created_at?: string
          id?: string
          sequence_number?: number
          shipment_id?: string
          size?: Database["public"]["Enums"]["container_size"]
        }
        Relationships: [
          {
            foreignKeyName: "containers_shipment_id_fkey"
            columns: ["shipment_id"]
            isOneToOne: false
            referencedRelation: "shipments"
            referencedColumns: ["id"]
          },
        ]
      }
      cost_items: {
        Row: {
          category: Database["public"]["Enums"]["cost_category_code"]
          created_at: string
          id: string
          is_active: boolean
          name: string
          sort_order: number
        }
        Insert: {
          category: Database["public"]["Enums"]["cost_category_code"]
          created_at?: string
          id?: string
          is_active?: boolean
          name: string
          sort_order?: number
        }
        Update: {
          category?: Database["public"]["Enums"]["cost_category_code"]
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          sort_order?: number
        }
        Relationships: []
      }
      cost_prices: {
        Row: {
          amount: number
          cost_item_id: string
          created_at: string
          currency: string
          effective_at: string
          id: string
          notes: string | null
          recorded_by: string | null
          unit: string
        }
        Insert: {
          amount?: number
          cost_item_id: string
          created_at?: string
          currency: string
          effective_at?: string
          id?: string
          notes?: string | null
          recorded_by?: string | null
          unit: string
        }
        Update: {
          amount?: number
          cost_item_id?: string
          created_at?: string
          currency?: string
          effective_at?: string
          id?: string
          notes?: string | null
          recorded_by?: string | null
          unit?: string
        }
        Relationships: [
          {
            foreignKeyName: "cost_prices_cost_item_id_fkey"
            columns: ["cost_item_id"]
            isOneToOne: false
            referencedRelation: "cost_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cost_prices_recorded_by_fkey"
            columns: ["recorded_by"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      quality_grades: {
        Row: {
          code: string
          created_at: string
          display_name: string
          id: string
          is_active: boolean
          sort_order: number
          tier: string
        }
        Insert: {
          code: string
          created_at?: string
          display_name: string
          id?: string
          is_active?: boolean
          sort_order?: number
          tier: string
        }
        Update: {
          code?: string
          created_at?: string
          display_name?: string
          id?: string
          is_active?: boolean
          sort_order?: number
          tier?: string
        }
        Relationships: []
      }
      shipment_costs: {
        Row: {
          amount: number
          cost_item_id: string
          created_at: string
          currency: string
          id: string
          shipment_id: string
          unit: string
        }
        Insert: {
          amount: number
          cost_item_id: string
          created_at?: string
          currency: string
          id?: string
          shipment_id: string
          unit: string
        }
        Update: {
          amount?: number
          cost_item_id?: string
          created_at?: string
          currency?: string
          id?: string
          shipment_id?: string
          unit?: string
        }
        Relationships: [
          {
            foreignKeyName: "shipment_costs_cost_item_id_fkey"
            columns: ["cost_item_id"]
            isOneToOne: false
            referencedRelation: "cost_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shipment_costs_shipment_id_fkey"
            columns: ["shipment_id"]
            isOneToOne: false
            referencedRelation: "shipments"
            referencedColumns: ["id"]
          },
        ]
      }
      shipments: {
        Row: {
          admin_fixed_usd: number
          bag_weight_kg: number
          cloned_from_id: string | null
          created_at: string
          created_by: string | null
          date: string
          exchange_rate: number
          financing_months: number
          id: string
          interest_rate_annual: number
          isr_pct: number
          label: string | null
          merma_pct: number
          price_per_qq_gtq: number
          quantity_qq: number
          reference_code: string
          status: Database["public"]["Enums"]["shipment_status"]
          updated_at: string
        }
        Insert: {
          admin_fixed_usd?: number
          bag_weight_kg?: number
          cloned_from_id?: string | null
          created_at?: string
          created_by?: string | null
          date?: string
          exchange_rate: number
          financing_months?: number
          id?: string
          interest_rate_annual?: number
          isr_pct?: number
          label?: string | null
          merma_pct?: number
          price_per_qq_gtq: number
          quantity_qq: number
          reference_code: string
          status?: Database["public"]["Enums"]["shipment_status"]
          updated_at?: string
        }
        Update: {
          admin_fixed_usd?: number
          bag_weight_kg?: number
          cloned_from_id?: string | null
          created_at?: string
          created_by?: string | null
          date?: string
          exchange_rate?: number
          financing_months?: number
          id?: string
          interest_rate_annual?: number
          isr_pct?: number
          label?: string | null
          merma_pct?: number
          price_per_qq_gtq?: number
          quantity_qq?: number
          reference_code?: string
          status?: Database["public"]["Enums"]["shipment_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shipments_cloned_from_id_fkey"
            columns: ["cloned_from_id"]
            isOneToOne: false
            referencedRelation: "shipments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shipments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          created_at: string
          full_name: string
          id: string
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          full_name: string
          id: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          full_name?: string
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      generate_reference_code: { Args: never; Returns: string }
      get_user_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
    }
    Enums: {
      allocation_input_mode: "kilos" | "percentage"
      container_size: "20ft" | "40ft"
      cost_category_code:
        | "purchasing"
        | "maquila"
        | "export_fixed_20"
        | "export_var_20"
        | "export_fixed_40"
        | "export_var_40"
        | "invoice_variable"
        | "admin_fixed"
      shipment_status: "draft" | "in_progress" | "complete" | "cancelled"
      user_role: "master" | "operator" | "gerencia"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      allocation_input_mode: ["kilos", "percentage"],
      container_size: ["20ft", "40ft"],
      cost_category_code: [
        "purchasing",
        "maquila",
        "export_fixed_20",
        "export_var_20",
        "export_fixed_40",
        "export_var_40",
        "invoice_variable",
        "admin_fixed",
      ],
      shipment_status: ["draft", "in_progress", "complete", "cancelled"],
      user_role: ["master", "operator", "gerencia"],
    },
  },
} as const

// Convenience type aliases used across the app
export type CostCategoryCode = Database["public"]["Enums"]["cost_category_code"]
